package segundapractica.view;
import java.awt.BorderLayout;
import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import segundapractica.code.Arbol;
import segundapractica.code.Nodo;
import segundapractica.code.Persona;
import segundapractica.code.Simulador;

/**
 *
 * @author Esteban Salas
 */
public class ViewArbol extends javax.swing.JFrame {
    private Simulador simulador;
    private ArrayList<Persona> pendientes = new ArrayList<>();
    private ArrayList<Nodo> a = new ArrayList<>();
    private Nodo aux = new Nodo(null);
    private Arbol arbol;
    
    public ViewArbol() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGeneros = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        lblNombre = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblNacimiento = new javax.swing.JLabel();
        lblFallecimiento = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtNacimiento = new javax.swing.JTextField();
        txtFallecimiento = new javax.swing.JTextField();
        optMasculino = new javax.swing.JRadioButton();
        optFemenino = new javax.swing.JRadioButton();
        btnCrear = new javax.swing.JButton();
        lblTitulo2 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        boxPersonas = new javax.swing.JComboBox<>();
        lblPadre = new javax.swing.JLabel();
        lblMadre = new javax.swing.JLabel();
        boxHombres = new javax.swing.JComboBox<>();
        boxMujeres = new javax.swing.JComboBox<>();
        btnAsignarPadre = new javax.swing.JButton();
        btnAsignarMadre = new javax.swing.JButton();
        lblTitulo3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblHombres = new javax.swing.JLabel();
        lblMujeres = new javax.swing.JLabel();
        lblFallecidos = new javax.swing.JLabel();
        boxFallecidos = new javax.swing.JComboBox<>();
        btnInformacion = new javax.swing.JButton();
        lblHijo = new javax.swing.JLabel();
        boxHijos = new javax.swing.JComboBox<>();
        btnAsignarHijo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de Pruebas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        jPanel2.setOpaque(false);

        jDesktopPane1.setOpaque(false);

        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setMaximizable(true);
        jInternalFrame2.setResizable(true);
        jInternalFrame2.setEnabled(false);
        jInternalFrame2.setFocusCycleRoot(false);
        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jInternalFrame2);
        jInternalFrame2.setBounds(0, 0, 590, 610);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        lblNombre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");

        lblTitulo1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("= - = Creacion de Personas = - =");
        lblTitulo1.setToolTipText("Aqui debes ingresar toda la información de la persona que deseas, luego haz click en el botón \"Crear\" para añadirla.");

        lblApellido.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellido.setText("Apellido:");

        lblGenero.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblGenero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGenero.setText("Genero:");

        lblEdad.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblEdad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEdad.setText("Edad:");

        lblCiudad.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblCiudad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCiudad.setText("Ciudad:");

        lblNacimiento.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNacimiento.setText("Fecha de Nacimiento:");

        lblFallecimiento.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblFallecimiento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFallecimiento.setText("Fecha de Fallecimiento:");

        txtNombre.setPreferredSize(new java.awt.Dimension(64, 24));

        txtApellido.setPreferredSize(new java.awt.Dimension(64, 24));

        txtEdad.setPreferredSize(new java.awt.Dimension(64, 24));

        txtCiudad.setPreferredSize(new java.awt.Dimension(64, 24));

        txtNacimiento.setPreferredSize(new java.awt.Dimension(64, 24));

        txtFallecimiento.setPreferredSize(new java.awt.Dimension(64, 24));

        btGeneros.add(optMasculino);
        optMasculino.setText("Masculino");

        btGeneros.add(optFemenino);
        optFemenino.setText("Femenino");

        btnCrear.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        lblTitulo2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo2.setText("= - = - = - Asignaciones - = - = - =");
        lblTitulo2.setToolTipText("Aqui debes ingresar toda la información de la persona que deseas, luego haz click en el botón \"Crear\" para añadirla.");

        btnSeleccionar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        lblPadre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblPadre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPadre.setText("Padre:");

        lblMadre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblMadre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMadre.setText("Madre:");

        boxHombres.setEnabled(false);

        boxMujeres.setEnabled(false);

        btnAsignarPadre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btnAsignarPadre.setText("Asignar");
        btnAsignarPadre.setEnabled(false);
        btnAsignarPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarPadreActionPerformed(evt);
            }
        });

        btnAsignarMadre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btnAsignarMadre.setText("Asignar");
        btnAsignarMadre.setEnabled(false);
        btnAsignarMadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarMadreActionPerformed(evt);
            }
        });

        lblTitulo3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo3.setText("= - = - = - Información - = - = - =");
        lblTitulo3.setToolTipText("Aqui debes ingresar toda la información de la persona que deseas, luego haz click en el botón \"Crear\" para añadirla.");

        lblTotal.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("Personas del arbol: 0");

        lblHombres.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblHombres.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHombres.setText("Hombres: 0");

        lblMujeres.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblMujeres.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMujeres.setText("Mujeres: 0");

        lblFallecidos.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblFallecidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFallecidos.setText("Han fallecido: 0");

        btnInformacion.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btnInformacion.setText("i");
        btnInformacion.setEnabled(false);
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });

        lblHijo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblHijo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHijo.setText("Hijo:");

        boxHijos.setEnabled(false);

        btnAsignarHijo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        btnAsignarHijo.setText("Asignar");
        btnAsignarHijo.setEnabled(false);
        btnAsignarHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarHijoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFallecimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtFallecimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(optMasculino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(optFemenino))
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(boxMujeres, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAsignarMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(boxHombres, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAsignarPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblHijo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(boxHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAsignarHijo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHombres, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMujeres, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFallecidos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(boxFallecidos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(lblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(625, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellido)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(optMasculino))
                            .addComponent(optFemenino, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEdad)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCiudad)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNacimiento)
                            .addComponent(txtNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFallecimiento)
                            .addComponent(txtFallecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInformacion))
                            .addComponent(boxPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPadre)
                            .addComponent(btnAsignarPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxHombres, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMadre)
                            .addComponent(boxMujeres, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(btnAsignarMadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHijo)
                            .addComponent(boxHijos, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(btnAsignarHijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHombres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMujeres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFallecidos)
                            .addComponent(boxFallecidos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(606, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarTxt(){
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.txtCiudad.setText("");
        this.txtNacimiento.setText("");
        this.txtFallecimiento.setText("");
        this.txtEdad.setText("");
        this.optMasculino.setSelected(false);
        this.optFemenino.setSelected(false);
    }
    
    public boolean verificarTxt(){
        // Nombre
        if(this.txtNombre.getText().isEmpty() || isNumeric(this.txtNombre.getText())){
            JOptionPane.showMessageDialog(null, "No has escrito un nombre valido", "ERROR: nombre", JOptionPane.ERROR_MESSAGE);
            this.txtNombre.setText("");
            return false;
        }else if(this.txtApellido.getText().isEmpty() || isNumeric(this.txtNombre.getText())){
            JOptionPane.showMessageDialog(null, "No has escrito un apellido valido", "ERROR: apellido", JOptionPane.ERROR_MESSAGE);
            this.txtApellido.setText("");
            return false;
        }else if(this.btGeneros.getSelection() == null){
            JOptionPane.showMessageDialog(null, "No has seleccionado un genero", "ERROR: genero", JOptionPane.ERROR_MESSAGE);
            return false;
        }else if(!isNumeric(this.txtEdad.getText())){
            JOptionPane.showMessageDialog(null, "No has escrito una edad valida", "ERROR: edad", JOptionPane.ERROR_MESSAGE);
            this.txtEdad.setText("");
            return false;
        }else if(this.txtCiudad.getText().isEmpty() || isNumeric(this.txtCiudad.getText())){
            JOptionPane.showMessageDialog(null, "No has escrito una ciudad validad", "ERROR: ciudad", JOptionPane.ERROR_MESSAGE);
            this.txtCiudad.setText("");
            return false;
        }else if(verificarFecha(this.txtNacimiento.getText()) == false){
            JOptionPane.showMessageDialog(null, "No has escrito una fecha valida (DD-MM-AAAA)", "ERROR: fecha nacimiento", JOptionPane.ERROR_MESSAGE);
            this.txtNacimiento.setText("");
            return false;
        }else if(!this.txtFallecimiento.getText().isEmpty()){
            if(verificarFecha(this.txtFallecimiento.getText()) == false){
                JOptionPane.showMessageDialog(null, "No has escrito una fecha valida (DD-MM-AAAA)", "ERROR: fecha fallecimiento", JOptionPane.ERROR_MESSAGE);
                this.txtFallecimiento.setText("");
                return false;
            }
        }
        return true;
    }
    
    public boolean verificarFecha(String fecha){
        String[] auxiliar = fecha.split("-");
        if(auxiliar.length != 3){
            return false;
        }else if(auxiliar[0].length() != 2 || !isNumeric(auxiliar[0])){
            return false;
        }else if(auxiliar[1].length() != 2 || !isNumeric(auxiliar[1])){
            return false;
        }else if(auxiliar[2].length() != 4 || !isNumeric(auxiliar[2])){
            return false;
        }else{
            return true;
        }
    }
    
    public boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
    
    public void llenarSeleccion(){
        boxPersonas.removeAllItems();
        a = arbol.recorrer(arbol.getRaiz(), null);
        for(int i = 0; i < a.size(); i++){
            Persona x = a.get(i).getPersona();
            boxPersonas.addItem(x.toString());
        }
    }
    
    public void llenarBox(){
        boxHombres.removeAllItems();
        boxMujeres.removeAllItems();
        boxHijos.removeAllItems();
        for(int i = 0; i < pendientes.size(); i++){
            Persona aux = pendientes.get(i);
            if(aux.getGenero() == 'M'){
                boxHombres.addItem(aux.toString());
            }
            if(aux.getGenero() == 'F'){
                boxMujeres.addItem(aux.toString());
            }
            boxHijos.addItem(aux.toString());
        }
    }
    
    public void complementos() {
        this.repintarArbol();
    }
    
    public void actualizarPendientes(){
        for(int i = 0; i < pendientes.size(); i++){
            for(int j = 0; j < a.size(); j++){
                if(pendientes.get(i) == a.get(j).getPersona()){
                    pendientes.remove(i);
                }
            }
        }
    }
    
    public void llenarInformacion(){
        boxFallecidos.removeAllItems();
        int nfallecidos = 0;
        int nhombres = 0;
        int nmujeres = 0;
        for(int i = 0; i < a.size(); i++){
            Nodo auxiliar = a.get(i);
            if(auxiliar.getPersona().estaMuerto()){
                boxFallecidos.addItem(auxiliar.getPersona().toString());
                nfallecidos += 1;              
            }
            if(auxiliar.getPersona().getGenero() == 'M'){
                nhombres += 1;
            }
            if(auxiliar.getPersona().getGenero() == 'F'){
                nmujeres += 1;
            }
        }  
        lblFallecidos.setText("Fallecidos: " + nfallecidos);
        lblHombres.setText("Hombres: " + nhombres);
        lblMujeres.setText("Mujeres: " + nmujeres);
        lblTotal.setText("Personas del arbol: " + a.size());
    }
    
    private void repintarArbol() {
        this.jDesktopPane1.removeAll();
        Rectangle tamaño = this.jInternalFrame2.getBounds();
        this.jInternalFrame2 = null;
        this.jInternalFrame2 = new JInternalFrame("Representación gráfica del árbol genealogico", true);
        this.jDesktopPane1.add(this.jInternalFrame2, JLayeredPane.DEFAULT_LAYER);
        this.jInternalFrame2.setVisible(true);
        this.jInternalFrame2.setBounds(tamaño);
        this.jInternalFrame2.setEnabled(false);
        this.jInternalFrame2.add(this.simulador.getDibujo(), BorderLayout.CENTER);
    }
    
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String nombre, apellido, ciudad, nacimiento, fallecimiento;
        char genero = 0;
        int edad;
        boolean continuar = verificarTxt();
        if(continuar == true){
            nombre = txtNombre.getText();
            apellido = txtApellido.getText();
            ciudad = txtCiudad.getText();
            nacimiento = txtNacimiento.getText();
            fallecimiento = txtFallecimiento.getText();
            edad = Integer.parseInt(txtEdad.getText());
            if(optMasculino.isSelected()){
                genero = 'M';
            }else if(optFemenino.isSelected()){
                genero = 'F';
            }
            Persona persona = new Persona(nombre, apellido, ciudad, genero, nacimiento, fallecimiento, edad);
            pendientes.add(persona);
            Nodo p = new Nodo(persona);
            if(arbol == null){
                arbol = new Arbol(p);
                simulador = new Simulador(p);
            }
            limpiarTxt();
            llenarSeleccion();
            llenarInformacion();
            actualizarPendientes();
            complementos();
        }  
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        if(aux.getPersona() == null){
            JOptionPane.showMessageDialog(null, "No has seleccionado ninguna persona", "ERROR: Seleccionar Persona", JOptionPane.ERROR_MESSAGE);
        }else{
            Persona per = aux.getPersona();
            Nodo persona = arbol.buscarNodo(per);
            ViewPersona view = new ViewPersona();
            view.asignarTextos(persona);
            view.setVisible(true);
        }
    }//GEN-LAST:event_btnInformacionActionPerformed

    private void btnAsignarPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarPadreActionPerformed
        String comp = boxHombres.getSelectedItem().toString();
        for(int i = 0; i < pendientes.size(); i++){
            if(pendientes.get(i).toString().equals(comp)){
                Nodo x = new Nodo(pendientes.get(i));
                arbol.asignar(1, aux, x);
                simulador.insertar(1, aux, x);
                pendientes.remove(i);
                boxHombres.setEnabled(false);
                btnAsignarPadre.setEnabled(false);
                actualizarPendientes();
                llenarSeleccion();
                llenarInformacion();
                llenarBox();
                complementos();
            }
        }
    }//GEN-LAST:event_btnAsignarPadreActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int i = boxPersonas.getSelectedIndex();
        aux = a.get(i);
        boxHijos.setEnabled(true);
        btnAsignarHijo.setEnabled(true);
        if(aux.getPadre() == null){
            boxHombres.setEnabled(true);
            btnAsignarPadre.setEnabled(true);
        }else{
            boxHombres.setEnabled(false);
            btnAsignarPadre.setEnabled(false);
        }
        if(aux.getMadre() == null){
            boxMujeres.setEnabled(true);
            btnAsignarMadre.setEnabled(true);
        }else{
            boxMujeres.setEnabled(false);
            btnAsignarMadre.setEnabled(false);
        }
        if(aux.getPersona() != null){
            btnInformacion.setEnabled(true);
        }else{
            btnInformacion.setEnabled(false);
        }
        llenarBox();
        actualizarPendientes();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnAsignarHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarHijoActionPerformed
        String comp = boxHijos.getSelectedItem().toString();
        for(int i = 0; i < pendientes.size(); i++){
            if(pendientes.get(i).toString().equals(comp)){
                Nodo x = new Nodo(pendientes.get(i));
                arbol.asignar(3, aux, x);
                simulador.insertar(3, aux, x);
                pendientes.remove(i);
                boxHijos.setEnabled(false);
                btnAsignarHijo.setEnabled(false);
                actualizarPendientes();
                llenarSeleccion();
                llenarInformacion();
                llenarBox();
                complementos();
            }
        }
    }//GEN-LAST:event_btnAsignarHijoActionPerformed

    private void btnAsignarMadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarMadreActionPerformed
        String comp = boxMujeres.getSelectedItem().toString();
        for(int i = 0; i < pendientes.size(); i++){
            if(pendientes.get(i).toString().equals(comp)){
                Nodo x = new Nodo(pendientes.get(i));
                arbol.asignar(2, aux, x);
                simulador.insertar(2, aux, x);
                pendientes.remove(i);
                boxMujeres.setEnabled(false);
                btnAsignarMadre.setEnabled(false);
                actualizarPendientes();
                llenarSeleccion();
                llenarInformacion();
                llenarBox();
                complementos();
            }
        }
    }//GEN-LAST:event_btnAsignarMadreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewArbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxFallecidos;
    private javax.swing.JComboBox<String> boxHijos;
    private javax.swing.JComboBox<String> boxHombres;
    private javax.swing.JComboBox<String> boxMujeres;
    private javax.swing.JComboBox<String> boxPersonas;
    private javax.swing.ButtonGroup btGeneros;
    private javax.swing.JButton btnAsignarHijo;
    private javax.swing.JButton btnAsignarMadre;
    private javax.swing.JButton btnAsignarPadre;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnInformacion;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblFallecidos;
    private javax.swing.JLabel lblFallecimiento;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblHijo;
    private javax.swing.JLabel lblHombres;
    private javax.swing.JLabel lblMadre;
    private javax.swing.JLabel lblMujeres;
    private javax.swing.JLabel lblNacimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPadre;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton optFemenino;
    private javax.swing.JRadioButton optMasculino;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFallecimiento;
    private javax.swing.JTextField txtNacimiento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
